rvm: '2.2.2'

script:
  - mkdir -p spec && bundle exec rspec spec

before_install:
- sed -i '2d' Gemfile
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3

before_script:
  - psql -c 'create database chitter_test;' -U postgres

addons:
code_climate:
  repo_token: ec85c57e123b7be517718f06d9f7f8e72623656073f9d4df0511fb84e87ee219
